name: AppMachine / Desktop (Electron)

on:
  push:
    tags: 
      - 'electron*'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    # Logic: If tag starts with 'electrondev', use Dev env. Otherwise Prod.
    environment: ${{ startsWith(github.ref, 'refs/tags/electrondev') && 'Development' || 'Production' }}
    env:
      APP_SERVER_URL: ${{ vars.APP_SERVER_URL }}
      APP_ID: ${{ vars.APP_ID }}
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build Electron App
        run: |
          set -euo pipefail

          # 1. Preflight Checks 🛡️
          if [ -z "${APP_SERVER_URL:-}" ]; then echo "❌ URL missing"; exit 1; fi

          # 2. Setup Temp Project 📂
          rm -rf .tmp_electron
          mkdir -p .tmp_electron
          cd .tmp_electron
          
          # Initialize & Install (Quietly)
          npm init -y > /dev/null
          npm install electron electron-builder --save-dev --silent

          # 3. Create Main Process (The "Brain") 🧠
          # We bake the URL directly into the window creation
          cat <<EOF > main.js
          const { app, BrowserWindow } = require('electron');
          
          function createWindow () {
            const win = new BrowserWindow({
              width: 1200,
              height: 800,
              title: "${APP_NAME}",
              webPreferences: { nodeIntegration: false }
            });
            // Load the remote URL directly
            win.loadURL('${APP_SERVER_URL}');
          }

          app.whenReady().then(createWindow);
          app.on('window-all-closed', () => {
            if (process.platform !== 'darwin') app.quit();
          });
          EOF

          # 4. Configure Builder (via package.json) ⚙️
          # We inject the build config and build script
          node -e '
            const fs = require("fs");
            const pkg = require("./package.json");
            
            pkg.name = "appmachine"; 
            pkg.productName = process.env.APP_NAME;
            pkg.version = "1.0.0";
            pkg.main = "main.js";
            
            // Electron Builder Config
            pkg.build = {
              appId: process.env.APP_ID,
              mac: {
                category: "public.app-category.productivity",
                target: ["zip"] 
              },
              directories: { output: "dist" }
            };
            
            pkg.scripts = { build: "electron-builder" };
            
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));
          '

          # 5. Build 🏗️
          npm run build

          # 6. Collect Artifact 📦
          cd dist
          ZIP="$(ls -1 *.zip | head -n 1)"
          
          if [ -z "${ZIP:-}" ]; then echo "❌ No zip found"; exit 1; fi
          
          echo "✅ Built: $ZIP"
          mv "$ZIP" "../../AppMachine-${GITHUB_REF_NAME}-electron.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppMachine-${{ github.ref_name }}-electron
          path: AppMachine-${{ github.ref_name }}-electron.zip
          if-no-files-found: error